### ISSUE TITLE
[BUG] failed to run the example

### ISSUE THREAD

**Issue by yiliu30** [intel/auto-round#244]
commit 5d92b25ccc0c937199d04101e1c4e7531c09e92f

- Reproduce the error 
```bash
# auto-round/examples/language-modeling
python main.py 
```
- Log
```bash
facebook/opt-125m
2024-09-08 21:50:14 INFO utils.py L443: Using GPU device
2024-09-08 21:50:17 INFO autoround.py L220: using torch.float16 for quantization tuning
Traceback (most recent call last):
  File "/xxx/auto-round/examples/language-modeling/main.py", line 352, in <module>
    deployment_device = args.deployment_device.split(',')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by yiliu30** [comment]
Reopen it as it failed again:

Follow `Enable marlin kernel` section at [README.md](https://github.com/intel/auto-round/blob/main/examples/language-modeling/README.md#2-run-examples): 
> CUDA_VISIBLE_DEVICES=0 python3 main.py --model_name facebook/opt-125m  --sym --bits 4 --group_size 128  --format "auto_round:gptq:marlin"

```
usr:language-modeling$ p main.py --sym --bits 4 --group_size 128  --format "auto_round:gptq:marlin"

Traceback (most recent call last):
  File "/home/path/3rd-party/auto-round/examples/language-modeling/main.py", line 180, in <module>
    assert False, "please only specify one of format and deployment_device"
           ^^^^^
AssertionError: please only specify one of format and deployment_device
```

**Comment by yiliu30** [comment]
@n1ck-guo, please have a look, thanks!
